

# DATASOURCE
datasource:
  url: "jdbc:postgresql://{DB_HOST}:{DB_PORT}/{DB_NAME}"
  username: "liquibase"
  password: "498d4840-8c47-460d"

# LIQUIBASE
liquibase:
  changelog:
    path: "db/changelog/changelog.xml"
    schema: "liquibase"
  default:
    schema: "entity"