---
# LIQUIBASE
liquibase:
  changelog-path: "db/changelog/changelog.xml"
  changelog-schema: "liquibase"
  default-schema: "entity"

# DATASOURCE
datasource:
  url: "jdbc:postgresql://${DB_HOST:postgres-db}:${DB_PORT:5432}/${DB_NAME:habits_app_db}"
  username: "liquibase"
  password: "498d4840-8c47-460d"

# JWT
jwt:
  access-token-expiration: 1
  refresh-token-expiration: 14
  role-key: "role"
  secret-string: "habits-app-yLRdtN3NsFRHKkThmB6EN2QXLxXGTPa7bgzx0pY72"
---